import React, { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'
import { Paragraph, Title } from '../styles/components/Text'
import { ButtonStyle } from '../styles/components/Button'
import { FlowingStyle, GrowTogetherStyle, ScreenMockupsStyle, UsersStyle } from '../styles/components/Ilustrations'
import Infos from '../components/Infos'
import { IconCommunitiesStyle, IconMessagesStyle } from '../styles/components/Icons'

const Home: NextPage = () => {
  const [widthDevice, setWidthDevice] = useState(0)

  useEffect(() => {
    setWidthDevice(window.innerWidth)
  }, [])

  const verifyWidth = widthDevice >= 1024

  return (
    <>
      <Head>
        <title>Huddle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section className='text_build' data-aos='zoom-in'>
          <Title>Build The Community Your Fans Will Love</Title>
          <Paragraph className='build-paragraph'>Huddle re-imagines the way we build communities. You have a
            voice, but so does your audience. Create connections with your users
            as you engage in genuine discussion.
          </Paragraph>
          <ButtonStyle style={{ marginTop: '2rem' }} fill="true">Get Started For Free</ButtonStyle>
        </section>

        <section className="mockup_image" data-aos='zoom-in'>
          <ScreenMockupsStyle/>
        </section>

        <section className='infos'>
          <Infos description="Communities Formed" icon={<IconCommunitiesStyle />} data={14} timer={70}>k</Infos>
          <Infos description="Messages Sent" icon={<IconMessagesStyle />} data={27} timer={80}>m+</Infos>
        </section>

        <section className="together" data-aos="fade-right" data-aos-delay="500">
          <img
            src={verifyWidth ? '/bg-section-top-desktop-1.svg' : '/bg-section-top-mobile-1.svg'}
            style={{ width: '100%', transform: 'translateY(6px)' }}
          />
          <div className='together-container'>
            <GrowTogetherStyle />
            <div className='text-together'>
            <Title style={{ marginTop: '2rem' }}>Grow Together</Title>
            <Paragraph className='TextTogether'>Generate meaningful discussions with your audience and build
              a strong, loyal community. Think of de insightful conversations you miss
              out on with a feedback form.
            </Paragraph>
            </div>
          </div>
          <img src={verifyWidth ? '/bg-section-bottom-desktop-1.svg' : '/bg-section-bottom-mobile-1.svg'} style={{ width: '100%' }}/>
        </section>

        <section className="flowing" data-aos="fade-left">
            <FlowingStyle/>
            <div className='flowing-text'>
            <Title style={{ marginTop: '2rem' }} >Flowing Conversations</Title>
            <Paragraph className='Textflowing' >You wouldn't paginate a conversation in real life,
              so why do it online? Our threads have just-in-time loading for a
              more natural flow.
            </Paragraph>
            </div>
        </section>

        <section className="users" data-aos="fade-right">
        <img src={verifyWidth ? '/bg-section-top-desktop-2.svg' : '/users-top.svg'} style={{ width: '100%', transform: 'translateY(6px)' }}/>
          <div>
            <UsersStyle/>
            <div className='user-text' >
            <Title style={{ marginTop: '2rem' }}>Your Users</Title>
            <Paragraph className='UserText'>It takes no time at all to integrate Huddle with your app's authentication solution.
              This means, once signed in to your app, your users can start
              chatting immediately.
            </Paragraph>
            </div>
          </div>
          <img src={verifyWidth ? '/bg-section-bottom-desktop-2.svg' : '/users-bottom.svg'} style={{ width: '100%' }}/>
        </section>

        <section className='text_ready'>
          <Title>Ready To Build Your Community?</Title>
          <ButtonStyle fill="true">Get Started For Free</ButtonStyle>
        </section>
      </Layout>
    </>
  )
}

export default Home
